### ISSUE TITLE
Improve concurrent queue processor

### ISSUE THREAD

**Issue by stooit** [quantcdn/drupal#18]
There is simple threaded queue processor support available via `drush quant:run-queue` however

* `pcntl_fork` should be used if available in php
* `pcntl_signal` used to capture `SIGINT` signals, and gracefully exit (won't work on Windows)
* additional support for limiting max number of items (divided by threads)

**Comment by kepol** [comment]
@stooit still relevant?

**Comment by steveworley** [comment]
The Quant drush commands support child threads and forking. This has been implemented.

https://github.com/quantcdn/drupal/blob/8.x-1.x/src/Commands/QuantDrushCommands.php#L73
