### ISSUE TITLE
Revisions and concurrency

### ISSUE THREAD

**Issue by steveworley** [quantcdn/drupal#24]

**Comment by kepol** [comment]
@steveworley What do you have in mind for this issue?

**Comment by kepol** [comment]
And is there overlap with this issue?

https://github.com/quantcdn/drupal/issues/18

**Comment by kepol** [comment]
Marking invalid for now since I'm not sure what is needed here.

**Comment by steveworley** [comment]
I don't remember what this one is about to be honest, let's close it for now and we can re-open if we need to address something more specifically. This is pretty broad.
