### ISSUE TITLE
`/taxonomy/term/id` redirects pushed multiple times for multi-lang setup

### ISSUE THREAD

**Issue by stooit** [quantcdn/drupal#31]
From umami seed logs
```
 [notice] [route_item] /en/tags/chocolate
 [notice] [redirect_item]: Source: /taxonomy/term/7, Dest: /en/tags/chocolate
 [notice] [route_item] /es/tags/chocolate
 [notice] [redirect_item]: Source: /taxonomy/term/7, Dest: /en/tags/chocolate
```

Shows the redirect from /taxonomy/term/7 to canonical default language url (/en/tags/chocolate) is pushed multiple times during seed. No functional issue, just not required.

Should only create the redirect when dealing with the default language.

**Comment by kepol** [comment]
I'll retest after the recent bug fixes.

**Comment by kepol** [comment]
Testing results:

Single language enabled

```
 [notice] [route_item] /tag1
 [notice] [redirect_item]: Source: /taxonomy/term/1, Dest: /tag1
 [notice] [route_item] /tag2
 [notice] [redirect_item]: Source: /taxonomy/term/2, Dest: /tag2
 [notice] [route_item] /term3
 [notice] [redirect_item]: Source: /taxonomy/term/3, Dest: /term3
```

Two languages enabled (more terms added)

```
 [notice] [redirect_item]: Source: /taxonomy/term/1, Dest: /en/tag1
 [notice] [route_item] /en/tag2
 [notice] [redirect_item]: Source: /taxonomy/term/2, Dest: /en/tag2
 [notice] [route_item] /en/term3
 [notice] [redirect_item]: Source: /taxonomy/term/3, Dest: /en/term3
 [notice] [route_item] /en/taxonomy/term/4
 [notice] [redirect_item]: Source: /taxonomy/term/4, Dest: /en/taxonomy/term/4
 [notice] [route_item] /en/tag5
 [notice] [redirect_item]: Source: /taxonomy/term/5, Dest: /en/tag5
```

Two languages enabled and one term translated

```
 [notice] [redirect_item]: Source: /taxonomy/term/1, Dest: /en/tag1
 [notice] [route_item] /ca/tag1
 [notice] [redirect_item]: Source: /taxonomy/term/1, Dest: /en/tag1
 [notice] [route_item] /en/tag2
 [notice] [redirect_item]: Source: /taxonomy/term/2, Dest: /en/tag2
 [notice] [route_item] /en/term3
 [notice] [redirect_item]: Source: /taxonomy/term/3, Dest: /en/term3
 [notice] [route_item] /en/taxonomy/term/4
 [notice] [redirect_item]: Source: /taxonomy/term/4, Dest: /en/taxonomy/term/4
 [notice] [route_item] /en/tag5
```

So this appears to be related to this bug:

https://github.com/quantcdn/drupal/issues/99

Though, when changing the paths for term 1 (for both languages), the redirects both show `/en` in Drupal:

<img width="1006" alt="screenshot" src="https://user-images.githubusercontent.com/282024/217999802-ae5e403e-d72c-4e23-88a9-2afdb67aa7d2.png">

But the redirects work as expected in Drupal.

**Comment by kepol** [comment]
This needs testing again now that #99 has been merged.

**Comment by kepol** [comment]
This is fixed. I changed the alias for a node and its translation and 2 redirects were created. These are handled as expected when seeding.

![Screenshot 2024-01-04 at 12 35 26 PM](https://github.com/quantcdn/drupal/assets/282024/d84adf64-4718-49fa-83c4-7da531a91593)

![Screenshot 2024-01-04 at 12 38 11 PM](https://github.com/quantcdn/drupal/assets/282024/b78cf18b-50fb-4bba-9868-f9d23fbff7af)

**Comment by kepol** [comment]
Synced to d.o for posterity:

https://www.drupal.org/project/quantcdn/issues/3412406
